// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storage

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthUser struct {
	Uuid         pgtype.UUID
	Username     string
	EmailAddress string
	Metadata     []byte
	CreatedAt    pgtype.Timestamp
	EditedAt     pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
	PhotoUrl     pgtype.Text
}
